/**
 * Created by S jawwad hashmi on 1/27/2017.
 */


export const GET_MISSING_PROCESS_ERROR = 'GET_MISSING_PROCESS_ERROR';
export const GET_MISSING_PROCESS_SUCCESS = 'GET_MISSING_PROCESS_SUCCESS';
export const GET_MISSING_PROCESS = 'GET_MISSING_PROCESS';


export const GET_CRIME_PROCESS_ERROR = 'GET_CRIME_PROCESS_ERROR';
export const GET_CRIME_PROCESS_SUCCESS = 'GET_CRIME_PROCESS_SUCCESS';
export const GET_CRIME_PROCESS = 'GET_CRIME_PROCESS';

export const GET_COMPLAIN_PROCESS_ERROR = 'GET_COMPLAIN_PROCESS_ERROR';
export const GET_COMPLAIN_PROCESS_SUCCESS = 'GET_COMPLAIN_PROCESS_SUCCESS';
export const GET_COMPLAIN_PROCESS = 'GET_COMPLAIN_PROCESS';

export const ADDREPORT_PROCESS_ERROR = 'ADDREPORT_PROCESS_ERROR';
export const ADDREPORT_PROCESS_SUCCESS = 'ADDREPORT_PROCESS_SUCCESS';
export const ADDREPORT_PROCESS = 'ADDREPORT_PROCESS';